package com.loongxun.cbe.enterprise.bean;

/**
 * Industrydatananly entity. @author MyEclipse Persistence Tools
 */
public class Industrydatananly extends AbstractIndustrydatananly implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Industrydatananly() {
	}

	/** minimal constructor */
	public Industrydatananly(Integer industryRatingNo, Integer lifeCycle,
			Double allTotalScores) {
		super(industryRatingNo, lifeCycle, allTotalScores);
	}

	/** full constructor */
	public Industrydatananly(Integer industryRatingNo, Integer lifeCycle,
			Double netAssetTarget, Double netAssetValue, Double fixAssetTarget,
			Double fixAssetValue, Double incomeTarget, Double incomeValue,
			Double profitTarget, Double profitValue, Double netbalTarget,
			Double netbalValue, Double scaleMeritTotalScores,
			Double liquidRatioTarget, Double liquidRatioValue,
			Double quickRatioTarget, Double quickRatioValue,
			Double cashRatioTarget, Double cashRatioValue,
			Double debtRatioTarget, Double debtRatioValue,
			Double equityRatioTarget, Double equityRatioValue,
			Double interestTimesTarget, Double interestTimesValue,
			Double shareholderRatioTarget, Double shareholderRatioValue,
			Double collateralRatioTarget, Double collateralRatioValue,
			Double debtTotalScores, Double totalAssetTurnRatioTarget,
			Double totalAssetTurnRatioValue, Double liquidAssetTurnRatioTarget,
			Double liquidAssetTurnRatioValue, Double fixAssetTurnRatioTarget,
			Double fixAssetTurnRatioValue, Double receivableTurnRatioTarget,
			Double receivableTurnRatioValue, Double stockTurnRatioTarget,
			Double stockTurnRatioValue, Double assetIncrementRatioTarget,
			Double assetIncrementRatioValue, Double saleGrowRatioTarget,
			Double saleGrowRatioValue, Double operationTotalScores,
			Double totalAssetReturnRatioTarget,
			Double totalAssetReturnRatioValue,
			Double netAssetReturnRatioTarget, Double netAssetReturnRatioValue,
			Double perfitCostRatioTarget, Double perfitCostRatioValue,
			Double afterTaxProfitTarget, Double afterTaxProfitValue,
			Double saleProfitTarget, Double saleProfitValue,
			Double earningTotalScores, Double totalAssetGrowRatioTarget,
			Double totalAssetGrowRatioValue, Double netAssetGrowRatioTarget,
			Double netAssetGrowRatioValue, Double totalIncomeGrowRatioTarget,
			Double totalIncomeGrowRatioValue, Double netIncomeGrowRatioTarget,
			Double netIncomeGrowRatioValue, Double mainBusProfitGrowTarget,
			Double mainBusProfitGrowValue, Double employeeGrowRatioTarget,
			Double employeeGrowRatioValue, Integer euntreponierAgeTarget,
			Double euntreponierAgeValue, Integer euntreponierDegreeTarget,
			Double euntreponierDegreeValue, Double euntreponierWorkTimeTarget,
			Double euntreponierWorkTimeValue,
			Integer euntreponierPopularyTarget,
			Double euntreponierPopularyValue, Integer developPlanTarget,
			Double developPlanValue, Integer developStrategyTarget,
			Double developStrategyValue, Integer qualityCertificateTarget,
			Double qualityCertificateValue, Integer industryNatureTarget,
			Double industryNatureValue, Double growthTotalScores,
			Double highTechIncomeRatioTarget, Double highTechIncomeRatioValue,
			Double rdinputRatioTarget, Double rdinputRatioValue,
			Double rdmoneyGrowRatioTarget, Double rdmoneyGrowRatioValue,
			Double collageRatioTarget, Double collageRatioValue,
			Integer technicalPayoffNumTarget, Double technicalPayoffNumValue,
			Integer iprnumTarget, Double iprnumValue, Integer patentNumTarget,
			Double patentNumValue, Integer govprojectNumLandTarget,
			Double govprojectNumLandValue, Integer govprojectNumProTarget,
			Double govprojectNumProValue, Integer govprojectNumCityTarget,
			Double govprojectNumCityValue, Integer incentiveTarget,
			Double incentiveValue, Integer rdorganizationTarget,
			Double rdorganizationValue, Integer investmentOrganizationTarget,
			Double investmentOrganizationValue, Integer internateCooTarget,
			Double internateCooValue, Integer lhdtarget, Double lhdvalue,
			Double creativeTotalScores, Double interestCoverageRatioTarget,
			Double interestCoverageRatioValue, Double loanOutdateRatioTarget,
			Double loanOutdateRatioValue, Double payMoneyRatioTarget,
			Double payMoneyRatioValue, Integer personalCreditTarget,
			Double personalCreditValue, Double creditExerciseTotalScores,
			Integer manageLevelTarget, Double manageLevelValue,
			Integer shareholderBackgroundTarget,
			Double shareholderBackgroundValue, String managerWorkTimeTarget,
			Double managerWorkTimeValue, Integer boardSizeTarget,
			Double boardSizeValue, Integer chairCeotarget,
			Double chairCeovalue, Integer auditOpinionTarget,
			Double auditOpinionValue, Integer illegalBehaviorTarget,
			Double illegalBehaviorValue, Integer managerAgeTarget,
			Double managerAgeValue, Integer managerEdubackgroundTarget,
			Double managerEdubackgroundValue, Integer managerTitalTarget,
			Double managerTitalValue, Double managerLevelTotalScores,
			Integer industryPolicyTarget, Double industryPolicyValue,
			Integer industryPositionTarget, Double industryPositionValue,
			Integer leaderIndustryNumTarget, Double leaderIndustryNumValue,
			Integer competitivePowerTarget, Double competitivePowerValue,
			Double marketCompeteTotalScores, Double allTotalScores,
			String createTime, Integer creditClassId, Boolean isHeavyIndustry) {
		super(industryRatingNo, lifeCycle, netAssetTarget, netAssetValue,
				fixAssetTarget, fixAssetValue, incomeTarget, incomeValue,
				profitTarget, profitValue, netbalTarget, netbalValue,
				scaleMeritTotalScores, liquidRatioTarget, liquidRatioValue,
				quickRatioTarget, quickRatioValue, cashRatioTarget,
				cashRatioValue, debtRatioTarget, debtRatioValue,
				equityRatioTarget, equityRatioValue, interestTimesTarget,
				interestTimesValue, shareholderRatioTarget,
				shareholderRatioValue, collateralRatioTarget,
				collateralRatioValue, debtTotalScores,
				totalAssetTurnRatioTarget, totalAssetTurnRatioValue,
				liquidAssetTurnRatioTarget, liquidAssetTurnRatioValue,
				fixAssetTurnRatioTarget, fixAssetTurnRatioValue,
				receivableTurnRatioTarget, receivableTurnRatioValue,
				stockTurnRatioTarget, stockTurnRatioValue,
				assetIncrementRatioTarget, assetIncrementRatioValue,
				saleGrowRatioTarget, saleGrowRatioValue, operationTotalScores,
				totalAssetReturnRatioTarget, totalAssetReturnRatioValue,
				netAssetReturnRatioTarget, netAssetReturnRatioValue,
				perfitCostRatioTarget, perfitCostRatioValue,
				afterTaxProfitTarget, afterTaxProfitValue, saleProfitTarget,
				saleProfitValue, earningTotalScores, totalAssetGrowRatioTarget,
				totalAssetGrowRatioValue, netAssetGrowRatioTarget,
				netAssetGrowRatioValue, totalIncomeGrowRatioTarget,
				totalIncomeGrowRatioValue, netIncomeGrowRatioTarget,
				netIncomeGrowRatioValue, mainBusProfitGrowTarget,
				mainBusProfitGrowValue, employeeGrowRatioTarget,
				employeeGrowRatioValue, euntreponierAgeTarget,
				euntreponierAgeValue, euntreponierDegreeTarget,
				euntreponierDegreeValue, euntreponierWorkTimeTarget,
				euntreponierWorkTimeValue, euntreponierPopularyTarget,
				euntreponierPopularyValue, developPlanTarget, developPlanValue,
				developStrategyTarget, developStrategyValue,
				qualityCertificateTarget, qualityCertificateValue,
				industryNatureTarget, industryNatureValue, growthTotalScores,
				highTechIncomeRatioTarget, highTechIncomeRatioValue,
				rdinputRatioTarget, rdinputRatioValue, rdmoneyGrowRatioTarget,
				rdmoneyGrowRatioValue, collageRatioTarget, collageRatioValue,
				technicalPayoffNumTarget, technicalPayoffNumValue,
				iprnumTarget, iprnumValue, patentNumTarget, patentNumValue,
				govprojectNumLandTarget, govprojectNumLandValue,
				govprojectNumProTarget, govprojectNumProValue,
				govprojectNumCityTarget, govprojectNumCityValue,
				incentiveTarget, incentiveValue, rdorganizationTarget,
				rdorganizationValue, investmentOrganizationTarget,
				investmentOrganizationValue, internateCooTarget,
				internateCooValue, lhdtarget, lhdvalue, creativeTotalScores,
				interestCoverageRatioTarget, interestCoverageRatioValue,
				loanOutdateRatioTarget, loanOutdateRatioValue,
				payMoneyRatioTarget, payMoneyRatioValue, personalCreditTarget,
				personalCreditValue, creditExerciseTotalScores,
				manageLevelTarget, manageLevelValue,
				shareholderBackgroundTarget, shareholderBackgroundValue,
				managerWorkTimeTarget, managerWorkTimeValue, boardSizeTarget,
				boardSizeValue, chairCeotarget, chairCeovalue,
				auditOpinionTarget, auditOpinionValue, illegalBehaviorTarget,
				illegalBehaviorValue, managerAgeTarget, managerAgeValue,
				managerEdubackgroundTarget, managerEdubackgroundValue,
				managerTitalTarget, managerTitalValue, managerLevelTotalScores,
				industryPolicyTarget, industryPolicyValue,
				industryPositionTarget, industryPositionValue,
				leaderIndustryNumTarget, leaderIndustryNumValue,
				competitivePowerTarget, competitivePowerValue,
				marketCompeteTotalScores, allTotalScores, createTime,
				creditClassId, isHeavyIndustry);
	}

}
